language: go
go: 1.5
sudo: false

env:
  global:
    - secure: "Q2G6nx07n89YKJo9lYOjFkejMo4psh/2iUV61OiwUaMSkGV1EhfYJJe0j9aKeTK4p/KKzx0QTRW+/o2l1HFH3mM++bs64j4Y9NUmAbgDtk8Pc2NCkRoSbpeNk+luB0aGdpSH7bJGncUzbfty3Yv3eQ9KB4fl9Y/CpuiDbTvmxGo="

install: go get github.com/koron/nvcheck
script:
  - sh ./tools/nvcheck.sh doc
  - sh ./tools/nvcheck.sh vim_faq

after_success:
  - sh ./tools/install_sshkey_github.sh "$CI_KEY" ./tools/ci@vimdoc-ja.vim-jp.org.enc ~/.ssh/ci@vimdoc-ja.vim-jp.org
  - git clone -b master --depth 1 git@github.com:vim-jp/vimdoc-ja-tmp.git _master
  # TODO: build master and copy its products to _master
  # TODO: commit and push to _master
  - git clone -b gh-pages --depth 1 git@github.com:vim-jp/vimdoc-ja-tmp.git _gh-pages
  # TODO: build gh-pages and copy its products to _gh-pages
  # TODO: commit and push to _gh-pages
