language: go
go: 1.5
sudo: false

env:
  global:
    - secure: "Q2G6nx07n89YKJo9lYOjFkejMo4psh/2iUV61OiwUaMSkGV1EhfYJJe0j9aKeTK4p/KKzx0QTRW+/o2l1HFH3mM++bs64j4Y9NUmAbgDtk8Pc2NCkRoSbpeNk+luB0aGdpSH7bJGncUzbfty3Yv3eQ9KB4fl9Y/CpuiDbTvmxGo="

install: go get github.com/koron/nvcheck

script:
  - make check

after_success:
  - sh ./tools/install_sshkey_github.sh "$CI_KEY" ./tools/ci@vimdoc-ja.vim-jp.org.enc ~/.ssh/ci@vimdoc-ja.vim-jp.org
  - '[ "$TRAVIS_BRANCH" == "working" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && sh ./tools/deploy-master.sh _master'
  - '[ "$TRAVIS_BRANCH" == "working" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && sh ./tools/deploy-gh-pages.sh _gh-pages'
